### ISSUE TITLE
Cross-module bytevec_impls

### ISSUE THREAD

**Issue by simon-whitehead** [fero23/bytevec#1]
Hi there,

The `bytevec_impls` macro defaults the accessibility of the structs to non-public. This stops them being used across modules.

Is it possible to allow a modifier to determine visibility? I tried it myself but unfortunately I am not very good at the Rust macro syntax. Its easy to copy+paste the whole macro and change the pattern but I was aiming for less code duplication. My final thought (untested) to reduce code duplication was to use the `include!` macro to pull in the bulk of the macro body from another file.. but that seemed lazy and so I didn't try it.

Thoughts?

**Comment by fero23** [comment]
Ah, certainly, I missed that on the macro declaration. I will add the pub modifier in the next version that should be released soon.

**Comment by fero23** [comment]
If you don't want to wait, I just merged https://github.com/fero23/bytevec/commit/bbff27d8787b84e50ae45c093c584764f9f5e455. With this commit, I renamed the `bytevec_impls` macro to `bytevec_decl`. `bytevec_decl` supports the pub identifier on the structure, but if you want to use pub on the `struct` fields, you will have to either use it on all of them or use none, because of limitations in the macro parsing language (I wish I could do something like 'or' in patterns). You can also use the new `bytevec_impls` macro to implement the traits on a `struct` you defined externally. You will have some duplicated code, but if `bytevec_decl` doesn't help you, this one should do the trick.

**Comment by simon-whitehead** [comment]
Impressive, thanks! This is great because I tried for about an hour to get a nice recursive macro happening exactly as you did in that commit - but I couldn't make it work as expected - so I have definitely learnt a lot from this commit. Thanks! :)

**Comment by fero23** [comment]
Great! Good to know it was useful to you. If you find something else lacking or you catch some bug, please open another issue. For now I will close this one.
